Prep css grid classes
poncej2/prep-0621-code-solutions pull request #9
Opened 2021-06-11 05:50 UTC by poncej2

<img width="1122" alt="Screen Shot 2021-06-10 at 10 45 21 PM" src="https://user-images.githubusercontent.com/85272726/121637407-2dcb1880-ca3e-11eb-8327-b84b25c1f68b.png">

2021-06-11 15:24 UTC, thebearingedge requested changes

2021-06-11 15:24 UTC, thebearingedge commented on prep-css-grid-classes/index.html
> +  <img style:width;100% src="images/crusade.png" alt="The Last Crusade" >
It's better to  put your styling in the CSS code instead of using a `style` attribute.

2021-06-12 04:33 UTC, poncej2 reviewed
I made a img rule set to style the width of the img. Removed the inline style from the img.

2021-06-12 16:16 UTC, thebearingedge approved these changes

2021-06-12 18:30 UTC, merged